# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884398fb0c2172db94728da4d1ee45d7e56814c21a89fa3b4aa717407c829df478fc329ddd696580f36703c3ea6c96fa696fc2a0be5c916e499aa8016ddb8650

test:
  secret_key_base: 8c7a2100459149ba7414dc227b78757b0b9c5a7ae6c2b258ee576f3f213a1cc3a9cb0f5b79565d27252e3ae1949c5d8c4eb791d370afd409de0be897262a3938

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
